# Generated by Django 5.0.6 on 2024-05-23 17:55

import blogcore.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogcore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profile_picture",
            field=models.ImageField(
                null=True,
                upload_to="blogcore/profile_picture",
                validators=[blogcore.validator.validate_file_size],
            ),
        ),
    ]
